### ISSUE TITLE
Bad interpreter: no such file or directory

### ISSUE THREAD

**Issue by dinhkhanh** [jschauma/gip#1]
When I run any `gip` command, even if `gip -h`, it says `zsh: /usr/local/bin/gip: bad interpreter: -Tw: no such file or directory`

I have JSON and Net::NetMask installed.

OS: MacOS 12
Device: Mac mini M1.

How can I solve this?

**Comment by jschauma** [comment]
Hmm, this sounds as if the first line of the script lost the path to perl. Or perhaps your shell doesn't like the second argument?  I can't reproduce this, but take a look and try the following:

1) What is the output of `head -1 /usr/local/bin/gip`?

2) Change it from `#! /usr/local/bin/perl -Tw` to `#! /usr/local/bin/perl -T`.

Let me know what the outcomes are.

**Comment by jschauma** [comment]
Ignore my last comment.  The problem was in the Makefile.  If you update and rerun `make clean; make install`, you should get a functional script.
